### ISSUE TITLE
Bash script doesn't work. Incorrect arguments for blueutil

### ISSUE THREAD

**Issue by edjw** [sonnyhuynh/alfred2-toggle-bluetooth#2]
The workflow doesn't work any more as it is. There has been a change in the arguments that blueutil uses. This is a working version. I opened a pull request to fix this.

```
PATH=/usr/local/bin:$PATH

if [ `blueutil --power` == "0" ] ; then
	blueutil --power 1
else
	blueutil --power 0
fi
```

**Comment by sonnyhuynh** [comment]
Yes thank you!
